### ISSUE TITLE
Kesalahan memulai bot

### ISSUE THREAD

**Issue by annklin** [raselcomel/mymd#1]
![Screenshot_20220104-021529_Termux](https://user-images.githubusercontent.com/71550518/148012715-ed92e955-4d18-47d4-a19e-3ebee36b50a9.jpg)
Mengapa ini terjadi?

**Comment by raseldev18** [comment]
Udh gua fix

**Comment by annklin** [comment]
> Udh gua fix

Kesalahan lain yang saya alami adalah di .on nsfw

Yang mengembalikan kesalahan berikut:

TypeError: Cannot set properties of undefined (setting 'nsfw')
    at Object.handler (/storage/emulated/0/Download/lucubot-md-multi-device/plugins/enable.js:118:22)
    at Object.handler (/storage/emulated/0/Download/lucubot-md-multi-device/handler.js:452:38)

**Comment by scoder37** [comment]
:v

**Comment by techwiz37** [comment]
kalau ada yg ditanyakan bisa bikin issue lgi
