### ISSUE TITLE
woy

### ISSUE THREAD

**Issue by techwiz37** [raselcomel/mymd#18]
tambahin pathmsg (untk fix hydrate) kyk di readme bailku lah anjg. pemakaimu pd minta tolong ke aku, males bet hrus cek" editin

**Comment by raseldev18** [comment]
kukira udh gada yg pake, sc ini udh gk keurus:v

**Comment by techwiz37** [comment]
males bet aku walaupun ez. ngerusak mod

**Comment by techwiz37** [comment]
menu nya fix sklian. ktnya ga muncl. mungkin perlu viewonce
